name: Deploy to Playstore

on:
  push:
    branches: [ "main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Generate local.properties
        run: |
          echo "googleApiKey=${{ secrets.GOOGLE_MAPS_API_KEY }}" >> local.properties
          echo "staticMapApiKey=${{ secrets.STATIC_MAPS_API_KEY }}" >> local.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> local.properties
          echo "keyAlias=${{ secrets.KEYSTORE_ALIAS }}" >> local.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> local.properties

      - name: Create google-services.json
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -di > app/google-services.json

      - name: Read version properties
        run: |
          while IFS='=' read -r key value || [[ -n "$key" ]]; do
            echo "Processing $key with value $value"
            case "$key" in
            "versionCode"|"versionMajor"|"versionMinor"|"versionPatch")
              echo "$key=$value" >> $GITHUB_ENV
              ;;
            esac
          done < versions.properties

      - name: Debug version variables
        run: |
          echo "VersionCode: ${{ env.versionCode }}"
          echo "VersionMajor: ${{ env.versionMajor }}"
          echo "VersionMinor: ${{ env.versionMinor }}"
          echo "VersionPatch: ${{ env.versionPatch }}"

      - name: Bump version
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{ env.versionCode }}
          versionName: 1.0.12

      - name: Assemble Release Bundle
        working-directory: ./
        run: ./gradlew bundleRelease

      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.PLAY_STORE_SIGNING_KEY }}
          alias: ${{ secrets.KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Deploy to Internal Testing
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_STORE }}
          packageName: com.albrivas.fuelpump
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: completed