name: Push

on:
  push:
    branches: ["main" ]
  pull_request:
  workflow_dispatch:


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
        - run: echo "The job was automatically triggered by a ${{ github.event_name }} event"
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'zulu'
            cache: gradle

        - name: Generate local.properties
          run: |
            echo "googleApiKey=${{ secrets.GOOGLE_MAPS_API_KEY }}" >> local.properties
            echo "staticMapApiKey=${{ secrets.STATIC_MAPS_API_KEY }}" >> local.properties

        - name: Create google-services.json
          env:
            DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
          run: echo $DATA | base64 -di > app/google-services.json
          
        # If gradlew is in the root directory, omit the property working-directory or else write ./
        - name: Grant execute permission for gradlew
          run: chmod +x gradlew
          working-directory: ./

        - name: Run detekt
          run: ./gradlew codeCheck
          working-directory: ./

        - name: Build with Gradle
          run: ./gradlew assembleDebug
          working-directory: ./
        
